version: "3.8"

services:
  # Development service
  web-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ../web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    # Enable hot reloading
    stdin_open: true
    tty: true
    command: yarn dev

  # Production service
  web-prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
